const uniqueCode = {
	unauthorizedOrigin: 'unauthorized_origin',
	unauthorizedRequest: 'unauthorized_request',
	noEmailPresent: 'no_email',
	invalidEmail: 'invalid_email',
	validEmail: 'valid_email',
	noFullNamePresent: 'no_full_name',
	invalidFullName: 'invalid_full_name',
	validFullName: 'valid_full_name',
	noAppNamePresent: 'no_app_name',
	invalidAppName: 'invalid_app_name',
	validAppName: 'valid_app_name',
	noAppDescriptionPresent: 'no_app_description',
	invalidAppDescription: 'invalid_app_description',
	validAppDescription: 'valid_app_description',
	noUserIdPresent: 'no_user_id',
	validUserId: 'valid_user_id',
	nonExistingUser: 'user_not_existing',
	userExists: 'user_exists',
	userCreated: 'user_created',
	userFetched: 'user_fetched',
	internalServerError: 'internal_server_error',
};

export default uniqueCode;
